---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    signalfx.com.custom.metrics: ""
  name: webservers
  namespace: hpa-example
spec:
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: nginx_requests
        selector:
          matchLabels:
            plugin: nginx
      target:
        type: AverageValue
        averageValue: "100"
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webservers

