---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    signalfx.com.custom.metrics: ""
  name: webservers
  namespace: hpa-example
spec:
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Object
    object:
      metric:
        name: nginx_requests
        selector:
          matchLabels:
            plugin: nginx
      describedObject:
        apiVersion: v1
        kind: Service
        name: webservers
      target:
        type: Value
        value: 1k
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webservers
