---
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.custom.metrics.k8s.io
  labels:
    app: {{ template "signalfx-metrics-adapter.name" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ template "signalfx-metrics-adapter.chart" . }}
spec:
  service:
    name: {{ template "signalfx-metrics-adapter.fullname" . }}-apiserver
    namespace: {{ .Release.Namespace }}
  group: custom.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
---
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.external.metrics.k8s.io
  labels:
    app: {{ template "signalfx-metrics-adapter.name" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ template "signalfx-metrics-adapter.chart" . }}
spec:
  service:
    name: {{ template "signalfx-metrics-adapter.fullname" . }}-apiserver
    namespace: {{ .Release.Namespace }}
  group: external.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
