---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "signalfx-metrics-adapter.fullname" . }}-auth-reader
  namespace: kube-system
  labels:
    app: {{ template "signalfx-metrics-adapter.name" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ template "signalfx-metrics-adapter.chart" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: {{ template "signalfx-metrics-adapter.fullname" . }}-apiserver
  namespace: {{ .Release.Namespace }}
