apiVersion: v1
kind: Secret
metadata:
  name: {{ template "signalfx-metrics-adapter.fullname" . }}
  labels:
    app: {{ template "signalfx-metrics-adapter.name" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ template "signalfx-metrics-adapter.chart" . }}
type: Opaque
data:
  access-token: {{ required "Access token must be provided" .Values.accessToken | b64enc | quote }}
